console.log('-----------------------------');
console.log('pirmas')
console.log('antras')
console.log('-----------------------------');
console.log('trečias')
console.log()
console.log('ketvirtas')
console.log('penktas')
console.log('šeštas')